# Generated by Django 2.1.2 on 2018-10-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='date_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
