# Generated by Django 2.0.2 on 2018-10-29 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_auto_20181028_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='date_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
