# Generated by Django 2.0.2 on 2018-10-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_auto_20181029_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='date_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
