# Generated by Django 2.1.2 on 2018-10-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noreg', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
